<?php

require_once dirname(__FILE__).'/autoload.php';

/**
 * Implements hook_boot().
 */
function oxygen_boot()
{
    $kernel = new Oxygen_Kernel(oxygen_container());
    $request = Oxygen_Http_Request::createFromGlobals();
    $kernel->handle($request);
}

/**
 * Get the service container singleton.
 *
 * @return Oxygen_Container_Production
 */
function oxygen_container()
{
    static $container;

    if ($container === null) {
        $container = new Oxygen_Container_Production();
    }

    return $container;
}
